
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - database_url=${database_url}
      - database_user=${database_user}
      - database_password=${database_password}
      - urls=${urls}
      - log_level=${log_level}
    networks:
      - app-network

#  frontend:
#   build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    depends_on:
#      - backend
#    ports:
#      - "4200:4200"
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge